/** @format */
import { type Metadata } from "next";
import { ThemeProvider } from "../providers/theme-provider";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import DashboardWrapper from "./dashboard-layot";

export const metadata: Metadata = {
  title: "GPS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="hrms-theme"
        >
          <DashboardWrapper>
            {children}
          </DashboardWrapper>

          <Toaster position="top-right" />
          <NextTopLoader
            color="var(--primary)"
            initialPosition={0.5}
            crawlSpeed={200}
            height={3}
            crawl
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px var(--primary), 0 0 5px var(--primary)"
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
